use addErrback after addCallback
the callback gets executed even in case of an error if errback is
specified before callback. This leads to

Error: This deferred has already been resolved

being thrown which then messes up with cleaning up sockets.

Now that my relay denies connections here and then due to anti spam
reasons, we'll had this happen quite often